version: "3.3"

services:
  amazons-server:
    build:
      context: .
      dockerfile: ./Server/Dockerfile
  amazons-ki:
    build:
      context: .
      dockerfile: ./KISpieler/Dockerfile
  hsa-server:
    build:
      context: hsa-server/
      dockerfile: ./Dockerfile
    depends_on:
      - amazons-server
      - amazons-ki
    environment:
      HSA_SERVER_URL: http://hsa-server
      PADERBORN_KI_PLAYER_URL: https://amazons-ki
      PADERBORN_SERVER_URL: https://amazons-server
